export const sampleText = `<h1>Prologue: The Wheel of Yugas</h1>
<p>Before time learned to count itself, before the first word was spoken into void, there existed the Beginning—the Primordial God whose breath became reality itself.</p>
<p>In the first moment of consciousness, the Beginning understood its own loneliness. So it created others like itself—Primordial Gods, vast and infinite, each a different aspect of existence. These beings, in turn, became creators themselves. They shaped gods to govern their designs, humans to experience them, and demons to test them. Creation sprawled outward, layer upon layer, hierarchy upon hierarchy, until it grew so vast across time and space that no single mind could comprehend its scope. Beginning and end became meaningless concepts in the face of infinite complexity.</p>
<p>But the Beginning made a choice that set it apart from all other Primordial Gods: it decided to participate in what had been created. While its siblings and children remained distant observers—architects admiring their work from beyond—the Beginning chose to descend. To be born. To live and die as part of creation rather than apart from it.</p>
<p>This was how the Yugas began—the cyclical sagas of existence itself.</p>
<p>Across infinite multiverses, the pattern repeats: the Beginning incarnates into mortal form, its presence igniting cosmic tensions that erupt into war between gods and demons, and at the conclusion, reality is remade. Four ages compose each Yuga: the golden age of truth, the age of ceremony, the age of doubt, and finally the age of darkness. At the end of every age, the Beginning returns in flesh, orchestrates a cataclysmic war, and the wheel turns to the next and anew.</p>
<p>Some universes welcome this cosmic reset. Others do not.</p>
<p>In countless realities, civilizations have learned to dread the incarnation. They see not renewal but endless suffering—worlds destroyed, lives erased, histories rendered meaningless by the whim of divine conflict. The Beginning cares nothing for mortal attachment. To the Primordial God, creation and destruction are merely the inhale and exhale of existence.</p>
<p>The Immortal Sage was born in one such universe that had learned to hate the wheel.</p>
<p>He watched his world burn in the war between gods and demons—a war sparked by the Beginning's incarnation, a war that treated humanity as kindling. While others prayed for salvation, the Sage studied the fundamental architecture of reality. While others accepted the Yuga as inevitable, he sought to do the impossible: to spit in the face of the Primordial God and stop the cycle forever.</p>
<p>His solution was radical. He could not kill the Beginning—nothing could. But he could starve it of its cyclical pleasures, delay its incarnation, make it powerless in this world.</p>
<p>The Sage shattered the connection between his world and the realm of Prana, the source of all magic. He created the Separation—a world of stagnation, severing divine power from mortal reality. Gods and demons alike were banished to the other side of an impenetrable barrier. Without magic, without divine interference, without the flow of Prana, the world would remain frozen in time—unable to grow, unable to evolve, unable to reach the conditions necessary for the Beginning's incarnation to trigger the next Yuga.</p>
<p>For three thousand years, it worked. Magic became myth. The incarnations ceased. Humanity survived in a dimmed world, but it survived.</p>
<p>Yet the Separation was always temporary. Like a dam holding back an infinite ocean, it could only delay the inevitable. Cracks formed. Prana began to seep through. And those who remembered the old ways—scavengers of forbidden knowledge, collectors of divine refuse—began to sense what was coming.</p>
<p>The Beginning would return. Not as a god descending from heaven, but as it always did: born mortal, fragile, unaware.</p>
<p>This is the story of one such incarnation in a dying industrial world called Dhūma—a realm that had forgotten gods, forgotten magic, forgotten even the stars themselves. In the capital city of Aethel Vane, where smoke choked the sky and ruins marked the landscape, the Beginning would wake as a sickly scavenger's son, knowing nothing of the cosmic war his very existence would ignite.</p>
<p>And this time, there were those who would try to use him before the wheels turned once again.</p>

<h1>Scavenger's Son</h1>
<p>The smoke hit Rishi's lungs before his eyes opened.</p>
<p>He jerked awake in the cramped sleeping quarters behind the scrap shop, coughing into his sleeve until his ribs burned. Through the single grimy window, the city sprawled beneath a colorless sky—no sun, no stars, only the perpetual gray that had hung over Aethel Vane for as long as anyone could remember. Collapsed towers jutted from the industrial wasteland like broken teeth. The air tasted of rust and ash.</p>
<p>"Get up," his mother called from the shop. Her voice held no warmth, only the sharp efficiency of someone who had long ago discarded anything that didn't aid survival. "The haul from District Nine came in. Sort it before the morning patrol."</p>
<p>Rishi pushed himself upright, ignoring the familiar ache in his joints. At fifteen, he looked twelve—gaunt, hollow-cheeked, his skin the color of old paper. He'd been sick his entire life, though no one could name the illness. His mother, Maya Vosh, attributed it to weakness. Fragile, she called him. Useless. The city's polluted air should have killed him years ago, but he persisted, clinging to life with the same stubborn resilience that kept the scavengers digging through ruins for scraps of the old world.</p>
<p>He stumbled into the shop, where his mother was already sorting through twisted metal and broken machinery. Maya was sharp angles and efficiency, her hands moving through the debris with the precision of a surgeon. She spared him a glance—measuring, dismissing—then gestured to a pile of corroded gears.</p>
<p>"Start there. And don't touch the electrical components. You'll ruin them."</p>
<p>Rishi knelt by the pile, his fingers trembling slightly as he separated salvageable pieces from waste. This was his life: sorting through the corpse of a world that had died before he was born, under the cold supervision of a mother who seemed to resent his existence. He told himself it didn't matter. Survival mattered. Nothing else.</p>
<p>But sometimes, late at night, he would climb to the roof and stare at the empty sky, feeling an inexplicable hunger gnaw at him—as if something vital had been stolen, as if the colorless void above should contain something his bones remembered but his mind could not name.</p>
<p style="text-align: center;">***</p>
<p>The bell above the shop door chimed.</p>
<p>Maya's hands went still. In fifteen years, Rishi had never seen his mother freeze.</p>
<p>A woman stood in the doorway, and she was wrong in every possible way. Her clothes were pristine white in a city that stained everything gray within hours. Her skin was pale as bone, her eyes the color of fresh blood—an albino, though Rishi had only read about such people in salvaged books. She moved with liquid grace, utterly unbothered by the smoke and grime that choked everything around her.</p>
<p>"Maya Vosh?" Her voice was soft, almost kind. "My name is Yuki. I am the Recruiter of the Incarnated, one of the highest ranked of the Theological Military. I've come for the boy."</p>
<p>Maya's hand shot out, grabbing a crowbar from beneath the counter. "Get out."</p>
<p>The woman tilted her head, surprised. "I represent the Kindred. You know what that means."</p>
<p>The crowbar shook in Maya's grip. Rishi had never seen his mother afraid before. Fear looked wrong on her, like rust on polished steel.</p>
<p>"He's sick," Maya said, her voice cracking. "He's weak. He's no use to you!"</p>
<p>"We're not looking for strength." Yuki's red eyes shifted to Rishi, and something flickered in her expression—recognition? curiosity? A strange melancholy, almost longing, as if she saw something in the boy she'd never had herself. An orphan recognizing what family looked like, even a broken one. Then her professional mask returned. "We're looking for potential. And this one... he burns so bright I could see him from across the city."</p>
<p>Shadows moved in the doorway. Two figures stepped into view, silent and armed, their faces hidden behind cloth masks. Guards. Enforcers. She couldn't fight against them.</p>
<p>Maya's shoulders sagged, and the crowbar clattered to the floor.</p>
<p>"Three days," she whispered. "Please, give me at least three days with my boy."</p>
<p>Yuki considered this, her head tilting again like a curious bird. Something softened in her expression—that melancholy deepening. Finally, she nodded. "Three days. Then I return, and he comes with me willingly or otherwise. Prepare him for his new life." She turned to leave, then paused at the threshold. "The Citadel awaits, Rishi Vosh. Elder Rahu will be eager to meet you."</p>
<p>When they were gone, when the bell had stopped chiming and the shop fell silent once more, Maya collapsed against the counter. Her whole body shook.</p>
<p>"Maa?" Rishi's voice was small, squeaking with fear.</p>
<p>She looked at him then, really looked at him, and for the first time in his life he saw something other than cold efficiency in her eyes. Something that might have been grief. Or love. Or terror.</p>
<p>"I tried to save you," she whispered. "I tried so hard."</p>
<p style="text-align: center;">***</p>
<p>For three days, everything changed.</p>
<p>Maya fed him real food—not the thin gruel and stale bread that had been his sustenance, but meat and vegetables salvaged from the better districts. She took him to the roof at night, where the empty sky stretched overhead, and told him stories of his grandmother who had known the stars before they vanished. His grandmother had been there when Dhūma was already in stagnation, but she'd passed down stories from her own parents—memories of when the only star visible was the sun, before even that had dimmed to perpetual gray.</p>
<p>On the third night, as they sat amid the smoke and ruins, Maya finally spoke the truth.</p>
<p>"You were dying from the moment you were born," she said, her voice hollow. "Not from the air or the pollution. From what you are. Your grandmother warned me. She said you carried something ancient, something that would consume you if I let it wake."</p>
<p>Rishi stared at her. "What are you talking about?"</p>
<p>"Magic." The word sounded like blasphemy. "It still exists, Rishi. Beyond the Separation. Beyond this dead world. And it's in you, trying to surface, trying to burn through your fragile body. So I starved it. I kept you weak, kept you hungry. Every cruel word, every punishment, every cold dismissal—I did it to keep you alive."</p>
<p>Understanding crashed through him like falling glass, but with it came something unexpected—relief. He'd always thought he was just a burden, a weight dragging her down. But this... "You were protecting me."</p>
<p>"I was killing you slowly so you wouldn't die quickly. I know I was harsh. I didn't want you to go out and be found, to become strong and become a danger to yourself." Maya's fingers trembled as she continued. "We hid here, in this symbol of collapse, because it was the last place anyone would look for something divine. Your father..." Her voice cracked. "He left us. You weren't born of him, Rishi. You were born of Divine Providence. When he realized what you were—or thought I had cheated—he couldn't stay. Housing an incarnated was worse than betrayal to him. So he separated himself from us, and I let him go."</p>
<p>Rishi felt his world tilt. "I don't have a father?"</p>
<p>"You have something more terrifying than a father." Maya's hand moved to the pendant around Rishi's neck—the small silver disk etched with symbols that seemed to shift in the dim light. He'd worn it for as long as he could remember, a weight so familiar he barely noticed it anymore. "This was your grandmother's. I always told you it would protect you. And it has—it's kept your power dormant, kept you weak enough to survive. I've heard of it being used to imprison kings." Her fingers trembled as she touched it. "I hoped it could protect you a little bit longer. But now..." She let her hand fall. "Now you need to wake up. And I can't stop that anymore."</p>
<p>"I don't understand," Rishi said. "What am I?"</p>
<p>"I don't know." For the first time, Maya touched him—her hand on his cheek, gentle and devastating. "But the Kindred do. They hunt children like you. Incarnates, they call them. Children touched by gods. And Rahu..." Her voice hardened. "Rahu collects them like tools."</p>
<p>"Then why let me go?"</p>
<p>"Because I can't stop them. And because..." She pulled him close, awkward and desperate, the embrace of someone who had forgotten how to show affection. "Because maybe you were never mine to keep. You belong to something bigger than this dying city. Bigger than me. Maybe... maybe I was wrong about everything. Maybe you were meant for more than hiding."</p>
<p>In her own twisted way, she had been protecting Rishi all along. And now, she was setting him free.</p>
<p style="text-align: center;">***</p>
<p>When Yuki returned on the fourth day, Rishi was ready. The pendant lay warm against his chest, its familiar weight now carrying new meaning—not just protection, but his mother's love, and the faith she'd placed in his grandmother's gift.</p>
<p>Maya stood in the doorway of the shop, her face a mask once more, but her eyes... her eyes told him everything.</p>
<p><i>I love you. I'm sorry. I should have told you when you were here with me. Survive.</i></p>
<p>Rishi followed Yuki into the smoke, into the waiting portal that would take him to the Citadel, into a destiny he couldn't begin to comprehend. Behind him, Maya Vosh stood alone in a shop full of broken things, and for the first time in fifteen years, she allowed herself to weep.</p>
<p>She regretted not telling him. Not saying the words. But perhaps he'd known anyway.</p>`;